### ISSUE TITLE
Cannot edit existing schedule after installing 0.30.03

### ISSUE THREAD

**Issue by maurizioandreotti60** [arthurdent75/SimpleScheduler#41]
I just updated to version 0.30.03 and now I can't edit existing schedules or create a new one.
Clicking the edit button does nothing.

**Comment by arthurdent75** [comment]
If you create a new scheduler are you able to edit it?

**Comment by maurizioandreotti60** [comment]
I can't create a new schedule. Clicking on the + button does nothing.
Tested with Firefox browser and HA Android App.

**Comment by arthurdent75** [comment]
Please, try to uninstall and install it again.
Scheduler should remain untouched, but just to be sure save all the JSON files

**Comment by maurizioandreotti60** [comment]
Where are stored JSON files?

**Comment by maurizioandreotti60** [comment]
I unistalled and installed again but the issue remains.
I noticed this message in the log when scheduler starts:
_rm: cannot remove '/share/simplescheduler/options.json': No such file or directory_

**Comment by maurizioandreotti60** [comment]
One more test.
Uninsstalled Simple Scheduler
Removed folder "simplescheduler"
Installed Simple Scheduler
Started Simple Scheduler and created new empty folder "simplescheduler"
Same issue, cannot create new schedule
Copied JSON files to folder "simplescheduler"
I can't edit the schedules

**Comment by maurizioandreotti60** [comment]
Justo noticed these errors in the browser console when I open the Simple Scheduler web page.
![immagine](https://user-images.githubusercontent.com/27202392/124187348-00620f80-dabe-11eb-8796-c878fa6b02c0.png)

**Comment by arthurdent75** [comment]
Those errors in the browser are not related to the addon.
By the way, it is really odd. 
Give me some time to create a new installation of HA and run some tests.

**Comment by maurizioandreotti60** [comment]
I can confirm that the issue is not caused by the new version. Just installed in a test instance of HA and it works fine.
I reverted to 0.22 in the production HA and the issue still exists, so it is something weird in my HA installation.

**Comment by maurizioandreotti60** [comment]
Looking at the log I see many occurences of this error:
Warning: Invalid argument supplied for foreach() in /var/www/html/lib.php on line 58

**Comment by arthurdent75** [comment]
> Looking at the log I see many occurences of this error:
> Warning: Invalid argument supplied for foreach() in /var/www/html/lib.php on line 58

Thank you for making such an effort to debug this.
Based on the line of the error, it seems that it can not get the list of the entities from the HA Rest API so there is something that is going definetively wrong with your HA.
Can you please write down which version of HA are you using in the production environment?

**Comment by maurizioandreotti60** [comment]
Actually I run HA 2021.6.6 with HassOS 6.1

**Comment by redneckdba** [comment]
Hi, I'm having exactly the same issue after upgrading the add-on to 0.30.03.
HA 2021.6.6 running on HA OS 6.1 as well.

**Comment by arthurdent75** [comment]
> Actually I run HA 2021.6.6 with HassOS 6.1

> HA 2021.6.6 running on HA OS 6.1 as well.

I have the same configuration, with no issue... this is odd...

**Comment by maurizioandreotti60** [comment]
> 
> 
> Hi, I'm having exactly the same issue after upgrading the add-on to 0.30.03.
> HA 2021.6.6 running on HA OS 6.1 as well.

I installed the latest Simple Scheduler in a test HA instance similar to the production one and it works fine.
So I suspect any interaction with a custom element for Lovelace.
Actually I'm using:
- Card mod
- Fold-entity-row
- Card tool
- Bar card
- Buttom card
- Entity attribute card
- Text divider row
Do you use any of those?

**Comment by redneckdba** [comment]
From what I can see I'm using the following custom elements, installed via HACS:
- Battery Entity Row
- slider-entitiy-row

**Comment by redneckdba** [comment]
Weird, I just removed all  custom elements from my HA installation and right after restarting it I got the previously mentioned php error mesage on line 58 of lib.php in a 2nd HA windows which was still on SimpleScheduler. In that window I was then able to add new schedules, however as soon as I navigated away and back to the Scheduler I was unable to modify the previously added one nor add new ones.

**Comment by arthurdent75** [comment]
Thank you guys for all the effort you are putting into this.
This issue seems to be JS related. Basically something interfere with the JS and prevent the click events from being executed. Usually this cause some kind of error in the browser console log but, as you can see, there is no trace of that, at least in the screenshot.

I will try to create a beta with a more detailed log, so with your help I could try to figure out the line 58 issue

**Comment by burntoc** [comment]
Thanks for taking a look @arthurdent75.  I'm definitely seeing this, too, though I didn't notice it until I went to 2021.7.1,  Happy to help troubleshoot when the beta is out.

**Comment by pbanj** [comment]
ya im getting the same thing
im on 2021.7.2

**Comment by arthurdent75** [comment]
It would be helpfull is someone skilled could run this test: force the sidebar to be visible by disabling the "display:none" attribute on the <nav id="sidebar" ...> in the browser inspector:

![Immagine 2021-07-14 142524](https://user-images.githubusercontent.com/60071192/125621916-70d75ca6-a911-42d6-bc06-3bf58cf051e2.png)

then add here a screenshot

**Comment by redneckdba** [comment]
Hi, 
this is how the sidebar looks like on my after setting display: none.
![image](https://user-images.githubusercontent.com/57302428/125623397-9fd7e680-5b27-4708-a032-26abe6cc264e.png)

**Comment by arthurdent75** [comment]
Please, click on pencil button first (it should populate the sidebar), then do the edit+screenshot
Thank you so much

**Comment by redneckdba** [comment]
Hi @arthurdent75 
Ok, I tried that and when switching disabling display: none I'm still getting an empty sidebar as seen below or maybe I'm missing some steps here. Also I'm still seeing some uncaught JS exceptions in the console.
![image](https://user-images.githubusercontent.com/57302428/125634556-23394649-b799-4f96-a7ee-653c7fd30787.png)

**Comment by redneckdba** [comment]
Oh, looks like I made some partial progress here. I had an automation which triggers Let's encrypt certificate renewal and was called "Let's Encrypt Renewal" and it seems like the single quote caused some JS errors and should be encoded when generating the list of available automations etc. in JS function $(document).on('click', '#addRow', function () {  of this addon. I'm now getting an empty sidebar when clicking on the + or edit button. Also I upgraded to version 0.30.04 of the addon.

**Comment by MPAndrew** [comment]
Hi, I have the same problem.
Home Assistant: 2021.7.2
Add-on: 0.30.04

**Comment by arthurdent75** [comment]
The new version 0.30.04 just uses newer versions of jquery and bootstrap. I just gave it a try.
The real problem here is that it is hard for me to figure it out because I can't replicate the issue...
Sorry to everyone!

**Comment by shvirik** [comment]
Hi guys,
Same problem too.

Core
Versión
core-2021.7.1

Supervisor
Versión
supervisor-2021.06.8

Error log:
rm: cannot remove '/share/simplescheduler/options.json': No such file or directory
But I think this error is not new.

Regards,

**Comment by rogercrespo** [comment]
Hello same problem. Made a migration from RPI to VM. After restore snapshot can't edit.

**Comment by arthurdent75** [comment]
> Error log:
> rm: cannot remove '/share/simplescheduler/options.json': No such file or directory
> But I think this error is not new.

Hi @shvirik you can safely ignore that error. 
At some point I decided to change the extension of the option file, so I try to remove older copy in case of upgrade.
The issue here is somehow related to Javascript and some kind conflict

**Comment by arthurdent75** [comment]
Can you guys tell me on what platform do you run HA?
Raspberry? x86? Virtual Machine?
Thanks to all of you!

**Comment by burntoc** [comment]
I'm on Home Asst Super used on a Pi 4.

**Comment by maurizioandreotti60** [comment]
I have the issue in a VM in Synology.
Anyway a second test instance on Synology is not affected.

**Comment by arthurdent75** [comment]
Ok everybody, I think I find out the issue!
Try to update to 0.30.05 and let me know!

**Comment by maurizioandreotti60** [comment]
Really sad to say that nothing changed with 0.30.05
HA 201.7.2 on VM - Synology

**Comment by arthurdent75** [comment]
> Really sad to say that nothing changed with 0.30.05

Could be a cache trouble.  The issue was due to a wrong external js library so maybe you are still loading the wrong one. Try to restart HASS and/or use a browser with an incognito window

**Comment by rogercrespo** [comment]
It's fixed! Thank you

**Comment by shvirik** [comment]
Yes!.... it's fixed in my HA too!!! THX!!!

Regards,

**Comment by maurizioandreotti60** [comment]
Cleared cache, restarted HA, used a differenza browser, issue still there.
I'll try again later.

**Comment by robycava** [comment]
Same issue:
- HA  core 2021.7.3 on RPI 4
- Simple Scheduler 0.30.05
- Tried different browsers. Same problem with companion iOS
- This notice in LOG: - [Sun Jul 18 13:51:32.763788 2021] [core:notice] [pid 15] AH00094: Command line: 'apache2 -D FOREGROUND'

Thanks for your job

**Comment by natosys** [comment]
Resolved for me.

**Comment by maurizioandreotti60** [comment]
I disinstalled Simple Scheduler and reinstalled, same problem.
I don't what else I can do.

**Comment by arthurdent75** [comment]
> I disinstalled Simple Scheduler and reinstalled, same problem.
> I don't what else I can do.

@maurizioandreotti60  I'm sorry to hear that.
What's your current issue on 0.30.05:  empty sidebar or no sidebar at all?

**Comment by maurizioandreotti60** [comment]
> > I disinstalled Simple Scheduler and reinstalled, same problem.
> > I don't what else I can do.
> 
> @maurizioandreotti60 I'm sorry to hear that.
> What's your current issue on 0.30.05: empty sidebar or no sidebar at all?

The sidebar is not opening at all. When I click on the pencil button, nothing happens. Clicking on the "+" is not working as well.

**Comment by supermemo007** [comment]
Hi all, same issue here not able to setup any schedule in the add-on
HA installed on Raspberry PI 3+
supervisor-2021.06.8  core-2021.7.3 current version simple scheduler 0.30.05
here my log from the add-on:
rm: cannot remove '/share/simplescheduler/options.json': No such file or directory
[Wed Jul 21 12:29:10.453004 2021] [mpm_prefork:notice] [pid 15] AH00163: Apache/2.4.38 (Debian) PHP/7.3.29 configured -- resuming normal operations
[Wed Jul 21 12:29:10.453202 2021] [core:notice] [pid 15] AH00094: Command line: 'apache2 -D FOREGROUND'
172.30.32.2 - - [21/Jul/2021:12:29:19 +0200] "GET / HTTP/1.1" 200 4932 "https://supermemo007.duckdns.org:8123/hassio" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
172.30.32.2 - - [21/Jul/2021:13:16:40 +0200] "GET / HTTP/1.1" 200 4932 "https://supermemo007.duckdns.org:8123/hassio" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"

my simple scheduler folder is :
➜  simplescheduler ls
options.dat    scheduler.log  sun.dat

already removed and reinstalled 
Any suggestion?
Thanks

**Comment by selectcarleasing** [comment]
all I updated today and have the issues folks are having, cant open the side bar or edit any existing schedules, I see the sidebar briefly on startup and then it just disappears.

**Comment by digginsa** [comment]
all I updated today and have the issues folks are having, cant open the side bar or edit any existing schedules, I see the sidebar briefly on startup and then it just disappears.

**Comment by arthurdent75** [comment]
I moved to bootstrap and jquery UI to maximize browser compatibility, but it seems I achieve the opposite.
I will work on a new release to undo that (as soon as I'll be back from holidays 🏖️)
I apologize to all of you, just be patient and wait for the new release.

**Comment by supermemo007** [comment]
> I moved to bootstrap and jquery UI to maximize browser compatibility, but it seems I achieve the opposite.
> I will work on a new release to undo that (as soon as I'll be back from holidays 🏖️)
> I apologize to all of you, just be patient and wait for the new release.


Many thanks for your great job here ! and enjoy your holidays !

**Comment by Energyboost** [comment]
same issue 

0.30.05

Supervisor Version | supervisor-2021.06.8

Operating System Version | 5.10.17-v8

Home Assistant 2021.7.4

**Comment by garylovesbeer1** [comment]
Same issue.
Press Plus button no response, no sidebar

Home Assistant Core Version core-2021.8.1

Host Operating System Home Assistant OS 6.2
Deployment production

Platform ProxMox

Log 
`rm: cannot remove '/share/simplescheduler/options.json': No such file or directory
[Sun Aug 22 13:28:07.843930 2021] [mpm_prefork:notice] [pid 15] AH00163: Apache/2.4.48 (Debian) PHP/7.3.29 configured -- resuming normal operations
[Sun Aug 22 13:28:07.844250 2021] [core:notice] [pid 15] AH00094: Command line: 'apache2 -D FOREGROUND'`

**Comment by arthurdent75** [comment]
>Home Assistant Core Version core-2021.8.1
>Host Operating System Home Assistant OS 6.2

I have the same in both production (RPi3) and many test environments (Virtualbox) without any error.
So, for sure, there is an interaction with some other addon or component.

Can you please tell me which other addon do you have?
Otherwise I'm not able to replicate the issue so it is really hard to find a solution.

Thanks to anybody who would give me any hints

**Comment by Energyboost** [comment]
ESPHome
File editor
Home Assistant Google Drive Backup
Mosquitto broker
Node-RED
Samba share
Spotify Connect
TasmoAdmin
Terminal & SSH

**Comment by bobmoran00** [comment]
How about making an earlier working version available, pre 0.30.03 until you can sort out the current issue?

**Comment by robycava** [comment]
Hi Arthurdent75,

my addons:

AirCast
Check Home Assistant Configuration
Duck DNS
File Editor
Home Assistant Google Drive Backup
Mosquitto broker
Node-RED
Samba share
NGINX Home Assistant SSL proxy
Network UPS Tools
SSH & Web Terminal
Visual Studio Code
Zigbee2mqtt


Integrations:

AVM FRITZ!Box Tools
AVM FRITZ!SmartHome
Alexa Media Player
Apple iCloud
Brother Printer
App per dispositivi mobili
Controllo alimentazione Raspberry Pi
Daikin AC
Deebot for Home Assistant
Ezviz
Google Cast
Home Assistant iOS
Home Connect
HomeKit
Meteorologisk institutt
MQTT
Netatmo
Philips TV
Shelly smart home
Synology DSM
Tile
Tuya
UPnP/IGD


HACS:

Node-RED Companion
ShellyForHass
Sonoff LAN
Spotcast


I can't edit or add any schedule in Simple Scheduler

Thanks, bye.

**Comment by burntoc** [comment]
Here are the addons I have:

AirCast
Check Home Assustabt configuration
File editor
Let's Encrypt
Mosquitto broker
Node-RED
Simple-Scheduler (of course)
Terminal & SSH
Z-Wave JS to MQTT
Zigbee2mqtt
Zigbee2mqtt Edge
deCONZ

**Comment by burntoc** [comment]
I haven't had time to test recreating my rules, but I can say I do see the
side slideout now to create a rule so fingers crossed we're good to go!
Thanks in advance!
